clear mex;clear all;close all;clc;
addpath(genpath(pwd));
load('agent');
load('valid_scenario');

HDMPC.Ns=4;
HDMPC.aaParam=struct('topology',...
                     {[],[1],[],[];[1],[],[1],[];[],[1],[],[1];[],[],[1],[]},...
                     'm',5,'droptol',1e-1,'beta',1,'AAstart',0,...
                     'smax',3e1,'atol',1e-4,'rtol',1e-4,'verbose',0);
HDMPC.nlpParam=struct('algorithm',NLOPT_LN_BOBYQA,...
                     'pi',[1;1;1;1],'rmin',[-1;-1;-1;-1],'rmax',[+1;+1;+1;+1],...
                     'kmax',1e2,'axtol',1e-4*ones(4,1),'aftol',1e-4,...
                     'initstep',1*ones(4,1),'verbose',0);
